[template variables]
COMPARE_OUTPUT=true
COMPARE_WALLCLOCK=true
COVERAGE=false
FCM_VERSION=''
HOUSEKEEPING=true
!!JASMIN_USER_ID='username'
REMOTE_JASMIN=false
!!REMOTE_JULES_SOURCE='/home/users/path/to/JULES/trunk'
RUN_NAMES=[]
SIMSYS_BRANCH="main"
SOURCE_JULES='.'
SUITE_TIMEOUT='PT15M'
USE_HEADS=false
USE_MIRRORS=false
USE_TOKENS=false
VN='vn8.2'
